name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt install cowsay 
      - uses: actions/checkout@v5
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay  # Affiche le contenu du fichier `README.md` à la base du dépôt